server:
  port: 9002

spring:
  application:
    name: note-service


eureka:
  client:
    service-url:
      default-zone=http: //localhost:8761
  instance:
    hostname: localhost

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761
#  instance:
#    hostname: localhost